### ISSUE TITLE
workers 部署方式，国内网络不能正常播放和下载视频，是否考虑pages部署方案

### ISSUE THREAD

**Issue by zhang33ya** [alist-org/cf-workers-proxy#3]
workers 部署时，国内运营商dns无法正常解析workers域名导致无法正常播放和下载视频；
经测试，切换dns服务商可以解决国内访问问题，但不够优雅。
是否考虑pages部署方案，pages域名国内目前是可以正常访问的。

**Comment by Unknow-404** [comment]
> workers 部署时，国内运营商dns无法正常解析workers域名导致无法正常播放和下载视频； 经测试，切换dns服务商可以解决国内访问问题，但不够优雅。 是否考虑pages部署方案，pages域名国内目前是可以正常访问的。

将Worker解析到自定义域
